name: dart_shelf_rest_api
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  dotenv: ^4.1.0
  http: ^0.13.5
  shelf: ^1.3.0
  shelf_router: ^1.1.2
  shelf_hotreload: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
